Description:
    This template deploys a group with a policy enabling users to switch to the new client account.
Parameters:
  ClientCode:
    Description: An Client Code that will be prefixed to resource names (aka "QSS")
    Type: String
  AccountID:
    Description: Please enter the ID for the Clients account that will be deployed to.
    Type: Number

Resources:   
  ClientUserGroup:
      Type: "AWS::IAM::Group"
      Properties:
          GroupName: ${ClientCode}WorkspacesAdministators
  ClientUserPolicy:    
      Type: "AWS::IAM::Policy"
      DependsOn: ClientUserGroup
      Properties: 
          Groups: !Ref ClientUserGroup
          PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
              - 
                  Sid: "Stmt1518568599000"
                  Effect: "Allow"
                  Action: 
                      - "sts:AssumeRole"
                  Resource: !Sub arn:aws:iam::${AccountID}:role/RoleSwitchAdmin
                  Condition: 
                    Bool: 
                      "aws:MultiFactorAuthPresent": "false"
          PolicyName: ${ClientCode}WorkspacesSwitchRolePolicy
Outputs:
    ClientUserPassword:
        Description: A quick link to add to our OneNote Documentation that will allow users to pre-fill the roleswitching information.
        Value: !Sub https://signin.aws.amazon.com/switchrole?account=${AccountID}&roleName=RoleSwitchAdmin&displayName=${ClientCode}-Workspaces 

